---
title: "miR-Dengue"
author: "Gabriel"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(openxlsx)
library(pheatmap)
library(factoextra); library(FactoMineR)
library(dendextend)
library(RColorBrewer)
library(EnhancedVolcano)
```

```{r}
files <- list.files(pattern = 'microRNAs')

df_mirnas <- read.xlsx('miR-plate-cod.xlsx')
# Criar um data frame vazio para armazenar os dados
combined_data <- data.frame()

# Loop para ler cada arquivo e adicionar como coluna no data frame
for (file in files) {
  # Extrair o nome da amostra do nome do arquivo
  sample_name <- sub("microRNAs-(.*)\\.xlsx", "\\1", file)
  sample_name <- gsub("-", ".", sample_name)
  # Ler o arquivo Excel
  data <- read.xlsx(file, startRow = 8, cols = 10, na.strings = "Undetermined", skipEmptyRows = F)
  #data <- as.data.frame(data)
  #data <- as.numeric(data)
  
  # Substituir as linhas 85 e 86 originais (cel-miR-39) e linhas originais 93-96 (controles de reação) pelas médias destas linhas
  # Isto para nomear as linhas com os miR unicos
  data[85, ] <- mean(c(data[85,], data[86,])) #Media cel-miR-39
  data <- data.frame(data[-86,]) #Remove duplicata cel-miR-39
  data[97, ] <- mean(c(data[92,], data[93,]))
  data[98, ] <- mean(c(data[94,], data[95,]))
  data <- as.data.frame(data[c(1:91,97,98),])
  
  # Supondo que os dados estão na primeira coluna do Excel
  if (ncol(combined_data) == 0) {
    combined_data <- data.frame(data[,1])
    colnames(combined_data) <- sample_name
  } else {
    combined_data[sample_name] <- data[,1]
  }
}
rownames(combined_data) <- df_mirnas[!duplicated(df_mirnas$miRNA.ID),]
CTs <- combined_data
#CTs <- na.omit(CTs)
CTs <- CTs[rowSums(is.na(CTs)) < 3,]
#Todos os valores 'undetermined' e >40 serão considerados com 40
#CTs[,c(1:6)] <- lapply(CTs[,c(1:6)], function(x){
#  ifelse(is.na(x), 50, x)
#})
```

#Repor NAs com média
```{r}
CTs.Grave <- CTs[,1:3]
CTs.SA <- CTs[,4:6]
CTs.SSA <- CTs[,7:9]

# Função para substituir NA pela média das outras duas colunas na linha
replace_na_with_row_mean <- function(row) {
  na_index <- is.na(row)
  if (sum(na_index) == 1) {
    row[na_index] <- mean(row[!na_index], na.rm = TRUE)
  }
  return(row)
}


CTs.Grave <- as.data.frame(t(apply(CTs.Grave, 1, replace_na_with_row_mean)))
CTs.SA <- as.data.frame(t(apply(CTs.SA, 1, replace_na_with_row_mean)))
CTs.SSA <- as.data.frame(t(apply(CTs.SSA, 1, replace_na_with_row_mean)))


##Adicionar quarta coluna de média
CTs.Grave$G.4_P <- rowMeans(CTs.Grave)
CTs.SA$SA.4_P <- rowMeans(CTs.SA)
CTs.SSA$SSA.4_P <- rowMeans(CTs.SSA)


CTs.full <- cbind(CTs.Grave, CTs.SA, CTs.SSA) %>% na.omit()
CTs.full <- CTs.full[c(-44,-43),]
```

#normalizacao
```{r}
dev <- CTs.full %>% rownames_to_column(., var="miRNA") %>% reshape2::melt(id_vars='miRNA') %>% group_by(miRNA) %>% rstatix::get_summary_stats(show=c('ci', 'sd'))



#x["SNORD61"]+x["SNORD68"]+x["SNORD72"]+x["SNORD95"]+x["SNORD96A"]
#dCT <-  apply(CTs, 2, function(x){
#  x - ((x["SNORD61"]+x["SNORD68"]+x["SNORD72"]+x["SNORD95"]+x["SNORD96A"])/5)
#})

dCT <-  apply(CTs.full, 2, function(x){
  x - ((x["hsa-miR-656-3p"]))
})

dCT <- dCT[!rowSums(dCT == 0) == ncol(dCT),]

dCT.2 <- data.frame(2^-(dCT))


Avg.dCT <- data.frame(Grave = round((rowMeans(dCT[,1:4])),2),
                      Con_signo = round((rowMeans(dCT[,5:8])),2),
                      Sin_Signo = round((rowMeans(dCT[,9:12])),2))
Avg.2.dCT <- 2^-(Avg.dCT)
```

#Fold change

###Função de t test
```{r}
# Função para aplicar o teste t a cada linha, dados os intervalos de colunas
apply_t_test <- function(df, cols_group1, cols_group2) {
  # Função interna para aplicar o teste t a uma linha específica
  apply_t_test_to_row <- function(row) {
    group1 <- as.numeric(row[cols_group1])
    group2 <- as.numeric(row[cols_group2])
    
    if (any(is.na(group1)) || any(is.na(group2))) {
      return(NA) # Retorna NA se houver valores NA na linha
    }
    
    t_test_result <- t.test(group1, group2)
    return(t_test_result$p.value)
  }
  
  # Aplicar a função a cada linha do dataframe
  p_values <- apply(df, 1, apply_t_test_to_row)
  
  # Ajustar os valores de p usando o método de Bonferroni
  adjusted_p_values <- p.adjust(p_values, method = "fdr")
  
  p_val <- data.frame(p_val = p_values, p.adj = adjusted_p_values)
  return(p_val)
}


```

Olhando a tabela de miRNA covid:
  FoldChange é calculado a partir da média dos valores de delta CT (2^(-Avg.Delta(CT))) como B/A, onde B = GOI e A = Control
```{r}
fc_grave.sa <- data.frame(FC_Grave_SA = Avg.2.dCT$Grave/Avg.2.dCT$Con_signo, row.names = rownames(Avg.2.dCT)) %>% 
  mutate(pval = apply_t_test(dCT.2, 1:4, 5:8)[,1],
         padj = apply_t_test(dCT.2, 1:4, 5:8)[,2])

fc_ssa.grave <- data.frame(FC_SSA_Grave = Avg.2.dCT$Sin_Signo/Avg.2.dCT$Grave, row.names = rownames(Avg.2.dCT)) %>% 
  mutate(pval = apply_t_test(dCT.2, 9:12, 1:4)[,1],
         padj = apply_t_test(dCT.2, 9:12, 1:4)[,2])

fc_ssa.sa <- data.frame(FC_SSA_SA = Avg.2.dCT$Sin_Signo/Avg.2.dCT$Con_signo, row.names = rownames(Avg.2.dCT)) %>% 
  mutate(pval = apply_t_test(dCT.2, 9:12, 5:8)[,1],
         padj = apply_t_test(dCT.2, 9:12, 5:8)[,2])

fc_grave.sa$log2fc <- log2(fc_grave.sa$FC_Grave_SA)
fc_ssa.grave$log2fc <- log2(fc_ssa.grave$FC_SSA_Grave)
fc_ssa.sa$log2fc <- log2(fc_ssa.sa$FC_SSA_SA)

```




#ddCT
```{r}
data.frame(apply(dCT[,1:3], 1, function(x) x - mean(dCT[, 5:6]))) %>% t(.)
```



#Clusterizacion
```{r}
#Criar dataframe com a identificacao de cada paciente em grupos
amostras <- data.frame(amostra=as.character(colnames(dCT.2)))
amostras$Condition <- c(rep("Grave", 4), rep("Signo de Alarma", 4), rep("Sin Signo de Alarma", 4))
amostras <- amostras %>% column_to_rownames("amostra")

#objeto com a selecao das cores gerais
cores <- c( "black", "yellow", "blue")
```
##Dendograma
```{r}
dist <- dist(t(dCT.2))
hc <- hclust(dist)
dend <- as.dendrogram(hc)
#plot(dend)

dend %>% 
  color_labels(labels = colnames(dCT.2[1:4]), col=cores[1]) %>%
  color_labels(labels = colnames(dCT.2[5:8]) , col=cores[2]) %>%
  color_labels(labels = colnames(dCT.2[9:12]), col=cores[3]) %>%
  plot() 
legend("topright",
       legend=c("Grave", "Con Signo", "Sin Signo"),
       col=cores,
       pch=c(20,20,20), bty = "n", pt.cex = 1.5, cex = .8)

```

##Distancia euclidiana
```{r}
dist.matrix <- as.matrix(dist)
pheatmap(dist.matrix,
         color=colorRampPalette(c("white", "blue"))(50),
         scale = "none",
         border_color = NA)
```

##Correlação
```{r}
breaksList = seq(-1,1, by = 0.02)

pheatmap(cor(dCT, method = "spearman"),
         #color=colorRampPalette(c("blue", "black", "yellow"))(100),
         color = colorRampPalette(rev(brewer.pal(n = 7, name = "PRGn")))(length(breaksList)), # Defines the vector of colors for the legend (it has to be of the same lenght of breaksList)
         breaks = breaksList,
         border=NA,
         cluster_rows = T,
         cluster_cols = T)
```

##Heatmap expressao
```{r}
pheatmap(dCT.2,
         border_color = NA,
         cluster_cols = F,
         color=colorRampPalette(c("blue", "black", "yellow"))(100),
         annotation_col = amostras,
         annotation_colors = list(Condition = c(Grave = cores[1],
                                                `Signo de Alarma` = cores[2],
                                                `Sin Signo de Alarma` = cores[3])),
         show_colnames = T,
         scale="row",
         legend_breaks = c(-2,0,2),
         legend_labels = c("Min", "Avg", "Max"))
```

##PCA
```{r}
pca <- PCA(t(dCT.2), graph = F)


fviz_pca_ind(pca,
             #geom.ind = "point",
             pointsize=4, pointshape=21,
             fill.ind = amostras$Condition,
             mean.point=F,
             addEllipses = T, ellipse.type="confidence",
             legend.title="Condition",
             title="")+
  theme_classic()+
  scale_fill_manual(values=cores)+ #legenda
  scale_color_manual(values=cores)
```

```{r}
EnhancedVolcano(fc_ssa.grave,
                lab=rownames(fc_ssa.grave),
                x="log2fc",
                y="padj", FCcutoff = 1, pCutoff = 0.05,
                title = "Sin signo alarma vs Grave", 
                ylim=c(0,5))
                #xlim=c(-7.5,7.5))

EnhancedVolcano(fc_ssa.sa,
                lab=rownames(fc_ssa.grave),
                x="log2fc",
                y="pval", FCcutoff = 1, pCutoff = 0.05)

EnhancedVolcano(fc_grave.sa,
                lab=rownames(fc_ssa.grave),
                x="log2fc",
                y="pval", FCcutoff = 1, pCutoff = 0.05,
                title="Grave vs SA")

```


```{r}
fc_ssa.grave %>% ggplot(aes(log2fc, rownames(.), fill=padj<0.05))+
  geom_col()+
  scale_fill_manual(values=c('grey', 'red4'), name="Significativo", labels=c("N.S", "*P adj <0.05"))+
  labs(y="miRNA", title= "SSA vs Grave")
```

